language: python
sudo: false

env:
  - LUA="lua 5.1"       COMPAT=default
  - LUA="lua 5.2"       COMPAT=default
  - LUA="lua 5.2"       COMPAT=none
  - LUA="lua 5.3"       COMPAT=default
  - LUA="lua 5.3"       COMPAT=none
  - LUA="luajit 2.0"    COMPAT=none
  - LUA="luajit 2.0"    COMPAT=all
  - LUA="luajit 2.1"    COMPAT=none
  - LUA="luajit 2.1"    COMPAT=all

before_install:
  - pip install hererocks
  - hererocks HERE --$LUA --compat $COMPAT --no-readline --luarocks latest --verbose
  - hererocks HERE --show
  - source HERE/bin/activate

install:
  - luarocks install luacheck

script: 
  # - luacheck --codes --std=max *.lua
  - lua valua-test.lua

after_success:

notifications:
  email:
    on_success: change
    on_failure: always
